version: "3"

# 设置mysql，redis持久化保存
volumes:
  postgres:
  redis:

services:
  web:
    build:
      context: ../../web
      dockerfile: ./Dockerfile
    container_name: cs-web
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
    command: ["nginx-debug", "-g", "daemon off;"]

  server:
    build:
      context: ../../server
      dockerfile: ./Dockerfile
    container_name: cs-server
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    network_mode: host

  postgres:
    image: postgres:13.3 # 使用PostgreSQL 13.3镜像
    container_name: cs-postgres
    hostname: cs-postgres
    restart: always
    ports:
      - "5432:5432" # host物理直接映射端口为15432
    environment:
      POSTGRES_DB: "postgres" # 初始化启动时要创建的数据库的名称，不设置空是为了避免新建一个和用户名同名的数据库，数据库初始化放到页面上
      POSTGRES_USER: "curescan" # 初始化启动时要创建的数据库的超级用户的用户名
      POSTGRES_PASSWORD: "H9nWDpM86K"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U curescan -d curescan"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0.6
    container_name: cs-redis # 容器名
    hostname: cs-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "ZtGf2B2T5b" # 设置Redis密码
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis:/data
